[package]
name = "bevy_runner"
version = "0.0.1"
edition = "2021"

[features]
default = [ ]

[dependencies]
bevy = "0.7"
bevy-parallax = "0.1.2"

[dev-dependencies]
bevy-inspector-egui = { version = "0.10.0", optional = true }
