[package]
name = "bevy_runner"
version = "0.0.1"
edition = "2021"

[features]
default = [ "ui-debug" ]
ui-debug = [ "dep:bevy-inspector-egui" ]
dist = []

[dependencies]
bevy = "0.7"
# bevy-parallax = "0.1.2"
heron = { version = "3.0.0", features = [ "2d", "debug-2d" ] }
bevy-parallax = { path = "../Contributions/Bevy/bevy-parallax" }
bevy-inspector-egui = { version = "0.10.0", optional = true }
