name: Deploy to store

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      username:
        required: true
        type: string
      channel:
        required: true
        type: string
      file:
        required: true
        type: string
      itch:
        required: true
        type: string
      token:
        required: true
        type: string


jobs:
  itch:
    runs-on: ubuntu-latest
    steps:
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: get_version
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ inputs.token }}
          file: ${{ inputs.file }}
          asset_name: ${{ inputs.name }}-${{ inputs.channel }}-${{ steps.get_version.outputs.tag }}.dmg
          tag: ${{ github.ref }}
          overwrite: true
      # Upload To Itch.io
      - if: ${{ inputs.channel  != 'wasm' }}
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ inputs.itch }}
          CHANNEL: ${{ inputs.channel }}
          ITCH_GAME: ${{ inputs.name }}
          ITCH_USER: ${{ inputs.username }}
          PACKAGE: ${{ inputs.file }}
